config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'home#index'

  resources :manufacturers
  resources :subsidiaries
  resources :car_categories
  resources :customers
  resources :car_models
  resources :cars

  resources :rentals do
    collection do
      match :search, via: :get, as: :search_by_token
    end
  end
end

app/models/subsidiary.rb
# frozen_string_literal: true

class Subsidiary < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :cnpj, presence: true, uniqueness: true, cnpj: true,
                   length: { is: 14 }, numericality: { only_integer: true }
  validates :address, presence: true

  def formatted_cnpj
    "#{cnpj[0..1]}.#{cnpj[2..4]}.#{cnpj[5..7]}/#{cnpj[8..11]}-#{cnpj[12..13]}"
  end
end

app/controllers/subsidiaries_controller.rb
# frozen_string_literal: true

class SubsidiariesController < ApplicationController
  def index
    @subsidiaries = Subsidiary.all
  end

  def show
    @subsidiary = Subsidiary.find params[:id]
  end

  def new
    @subsidiary = Subsidiary.new
  end

  def create
    @subsidiary = Subsidiary.new subsidiary_params
    if @subsidiary.save
      flash[:success] = t 'views.messages.successfully.created',
                          resource: t('activerecord.models.subsidiary.one')
      redirect_to @subsidiary
    else
      render :new
    end
  end

  def edit
    @subsidiary = Subsidiary.find params[:id]
  end

  def update
    @subsidiary = Subsidiary.find params[:id]
    if @subsidiary.update subsidiary_params
      flash[:success] = t 'views.messages.successfully.updated',
                          resource: t('activerecord.models.subsidiary.one')
      redirect_to @subsidiary
    else
      render :edit
    end
  end

  def destroy
    Subsidiary.find(params[:id]).destroy
    flash[:success] = t 'views.messages.successfully.destroyed',
                        resource: t('activerecord.models.subsidiary.one')
    redirect_to subsidiaries_url
  end

  private

  def subsidiary_params
    params.require(:subsidiary).permit :name, :cnpj, :address
  end
end

app/views/subsidiaries/_form.erb
<%= form_with model: @subsidiary, local: true, class: 'subsidiary_form' do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class='form-group'>
    <%= f.label :name, t('activerecord.attributes.subsidiary.name') %>
    <%= f.text_field :name, required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :cnpj, t('activerecord.attributes.subsidiary.cnpj') %>
    <%= f.text_field :cnpj, required: true, class: ['form-control', 'cnpj_input'] %>
  </div>

  <div class='form-group'>
    <%= f.label :address, t('activerecord.attributes.subsidiary.address') %>
    <%= f.text_field :address, required: true, class: 'form-control' %>
  </div>

  <%= f.submit t('views.actions.send'), class: 'btn btn-primary' %>
<% end %>

app/views/subsidiaries/edit.html.erb
<nav>
  <%= link_to t('views.navigation.go_back'), subsidiaries_path, class: 'btn btn-secondary' %>
</nav>

<main class='row'>
  <div class='col-md-12'>
    <header class='header'>
      <h1><%= t('views.actions.update') %> <%= t('activerecord.models.subsidiary.one') %></h1>
    </header>

    <section class='contents'>
      <%= render 'form' %>
    </section>

  </div>
</main>

app/views/subsidiaries/index.html.erb
<nav>
  <%= link_to t('views.navigation.go_back'), root_path, class: 'btn btn-secondary' %>
</nav>

<main class='row'>
  <div class='col-md-12'>
    <header class='header'>
      <h1><%= t('activerecord.models.subsidiary.other') %></h1>

      <p><%= t('views.resources.subsidiaries.description') %></p>
    </header>

    <section class='contents'>
      <% if @subsidiaries.empty? %>
        <p><%= t('views.resources.subsidiaries.empty_resource') %></p>
      <% end %>

      <table class="col index_table">
        <thead class="index_table_head">
          <tr class="index_table_row">
            <th><%= t('activerecord.attributes.subsidiary.name') %></th>
            <th><%= t('activerecord.attributes.subsidiary.cnpj') %></th>
            <th></th>
          </tr>
        </thead>

        <tbody class="index_table_body">
          <% @subsidiaries.each do |subsidiary| %>
            <tr class="index_table_row" id="subsidiary-<%= subsidiary.id %>">
              <td><%= subsidiary.name %></td>
              <td><%= subsidiary.formatted_cnpj %></td>
              <td><%= link_to t('views.navigation.details'), subsidiary, id: "details-#{subsidiary.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </section>

    <div class='actions mt-4'>
      <%= link_to  t('views.navigation.new'), new_subsidiary_path, class: 'btn btn-primary' %>
    </div>
  </div>
</main>

app/views/subsidiaries/new.html.erb
<nav>
  <%= link_to t('views.navigation.go_back'), subsidiaries_path, class: 'btn btn-secondary' %>
</nav>

<main class='row'>
  <div class='col-md-12'>
    <header class='header'>
      <h1><%= t('views.resources.subsidiaries.create') %></h1>
    </header>

    <section class='contents'>
      <%= render 'form' %>
    </section>

  </div>
</main>

app/views/subsidiaries/show.html.erb
<nav clas='col'>
  <%= link_to t('views.navigation.go_back'), subsidiaries_path, class: 'btn btn-secondary' %>
</nav>

<main class='row'>
  <div class='col-12'>
    <header class='header'>
      <h1> <%= @subsidiary.name %> </h1>
    </header>

    <section class='contents'>
      <dl>
        <dt><%= t('activerecord.attributes.subsidiary.cnpj') %>:</dt>
        <dd> <%= @subsidiary.formatted_cnpj %> </dd>
        <dt><%= t('activerecord.attributes.subsidiary.address') %>:</dt>
        <dd> <%= @subsidiary.address %> </dd>
      </dl>
    </section>

    <div class='actions mt-4'>
      <%= link_to t('views.navigation.edit'), edit_subsidiary_path(@subsidiary), class: 'btn btn-primary' %>
      <%= link_to t('views.actions.delete'), @subsidiary, method: :delete,
                  data: { confirm: t('views.messages.delete_resource', resource: @subsidiary.name) },
                  class: 'btn btn-danger' %>
    </div>
  </div>
</main>