config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'home#index'

  resources :manufacturers
  resources :subsidiaries
  resources :car_categories
  resources :customers
  resources :car_models
  resources :cars

  resources :rentals do
    collection do
      match :search, via: :get, as: :search_by_token
    end
  end
end

app/models/car_category.rb
# frozen_string_literal: true

class CarCategory < ApplicationRecord
  has_many :car_models, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :daily_rate, presence: true, numericality: { greater_than: 0 }
  validates :insurance, presence: true, numericality: { greater_than: 0 }
  validates :third_party_insurance, presence: true, numericality: { greater_than: 0 }
end

app/controllers/car_categories_controller.rb
# frozen_string_literal: true

class CarCategoriesController < ApplicationController
  def index
    @car_categories = CarCategory.all
  end

  def show
    @car_category = CarCategory.find params[:id]
  end

  def new
    @car_category = CarCategory.new
  end

  def create
    @car_category = CarCategory.new car_category_params
    if @car_category.save
      flash[:success] = t 'views.messages.successfully.created',
                          resource: t('activerecord.models.car_category.one')
      redirect_to @car_category
    else
      render :new
    end
  end

  def edit
    @car_category = CarCategory.find params[:id]
  end

  def update
    @car_category = CarCategory.find params[:id]
    if @car_category.update car_category_params
      flash[:success] = t 'views.messages.successfully.updated',
                          resource: t('activerecord.models.car_category.one')
      redirect_to @car_category
    else
      render :edit
    end
  end

  def destroy
    CarCategory.find(params[:id]).destroy
    flash[:success] = t 'views.messages.successfully.destroyed',
                        resource: t('activerecord.models.car_category.one')
    redirect_to car_categories_url
  end

  private

  def car_category_params
    params.require(:car_category).permit :name, :daily_rate, :insurance,
                                         :third_party_insurance
  end
end

app/views/car_categories/_form.erb
<%= form_with model: @car_category, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class='form-group'>
    <%= f.label :name, t('activerecord.attributes.car_category.name') %>
    <%= f.text_field :name, required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :daily_rate, t('activerecord.attributes.car_category.daily_rate') %>
    <%= f.number_field :daily_rate, min: 1, step: 0.01, required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :insurance, t('activerecord.attributes.car_category.insurance') %>
    <%= f.number_field :insurance, min: 1, step: 0.01, required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :third_party_insurance, t('activerecord.attributes.car_category.third_party_insurance') %>
    <%= f.number_field :third_party_insurance, min: 1, step: 0.01, required: true, class: 'form-control' %>
  </div>

  <%= f.submit t('views.actions.send'), class: 'btn btn-primary' %>
<% end %>

app/views/car_categories/edit.html.erb
<nav>
  <%= link_to t('views.navigation.go_back'), car_categories_path, class: 'btn btn-secondary' %>
</nav>

<main class='row'>
  <div class='col-md-12'>
    <header class='header'>
      <h1><%= t('views.actions.update') %> <%= t('activerecord.models.car_category.one') %></h1>
    </header>

    <section class='contents'>
      <%= render 'form' %>
    </section>

  </div>
</main>

app/views/car_categories/index.html.erb
<nav>
  <%= link_to t('views.navigation.go_back'), root_path, class: 'btn btn-secondary' %>
</nav>

<main class='row'>
  <div class='col-md-12'>
    <header class='header'>
      <h1><%= t('activerecord.models.car_category.other') %></h1>

      <p><%= t('views.resources.car_categories.description') %></p>
    </header>

    <section class='contents'>
      <% if @car_categories.empty? %>
        <p><%= t('views.resources.car_categories.empty_resource') %></p>
      <% end %>

      <table class="col index_table">
        <thead class="index_table_head">
          <tr class="index_table_row">
            <th><%= t('activerecord.attributes.car_category.name') %></th>
            <th><%= t('activerecord.attributes.car_category.daily_rate') %></th>
            <th><%= t('activerecord.models.car_model.other') %></th>
            <th></th>
          </tr>
        </thead>

        <tbody class="index_table_body">
          <% @car_categories.each do |car_category| %>
            <tr class="index_table_row" id="car-category-<%= car_category.id %>">
              <td><%= car_category.name %></td>
              <td><%= number_to_currency(car_category.daily_rate) %></td>

              <td class='dropdown'>
                <a class='dropdown-toggle' role='button' id='resourcesDropdown' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                  <%= t('views.actions.expand') %>
                </a>

                <div class='dropdown-menu' aria-labelledby='resourcesDropdown'>
                  <% car_category.car_models.each do |car_model| %>
                    <%= link_to "#{car_model.manufacturer.name} #{car_model.name} #{car_model.year}", car_model, class: 'dropdown-item' %>
                  <% end %>
                </div>
              </td>

              <td><%= link_to t('views.navigation.details'), car_category, id: "details-#{car_category.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </section>

    <div class='actions mt-4'>
      <%= link_to t('views.navigation.new'), new_car_category_path, class: 'btn btn-primary' %>
    </div>
  </div>
</main>

app/views/car_categories/new.html.erb
<nav>
  <%= link_to t('views.navigation.go_back'), car_categories_path, class: 'btn btn-secondary' %>
</nav>

<main class='row'>
  <div class='col-md-12'>
    <header class='header'>
      <h1><%= t('views.resources.car_categories.create') %></h1>
    </header>

    <section class='contents'>
      <%= render 'form' %>
    </section>

  </div>
</main>

app/views/car_categories/show.html.erb
<nav clas='col'>
  <%= link_to t('views.navigation.go_back'), car_categories_path, class: 'btn btn-secondary' %>
</nav>

<main class='row'>
  <div class='col-12'>
    <header class='header'>
      <h1> <%= t('activerecord.models.car_category.one') %> <%= @car_category.name %> </h1>
    </header>

    <section class='contents row'>
      <aside class="col-3">
        <dl class="side_info_box">
          <dt><%= t('activerecord.models.car_model.other') %>:</dt>
          <% @car_category.car_models.each do |car_model| %>
            <dd><%= link_to "#{car_model.manufacturer.name} #{car_model.name} #{car_model.year}", car_model %> </dd>
          <% end %>
        </dl>
      </aside>

      <dl>
        <dt><%= t('activerecord.attributes.car_category.daily_rate') %>:</dt>
        <dd> <%= number_to_currency(@car_category.daily_rate) %> </dd>
        <dt><%= t('activerecord.attributes.car_category.insurance') %>:</dt>
        <dd> <%= number_to_currency(@car_category.insurance) %> </dd>
        <dt><%= t('activerecord.attributes.car_category.third_party_insurance') %>:</dt>
        <dd> <%= number_to_currency(@car_category.third_party_insurance) %> </dd>
      </dl>
    </section>

    <div class='actions mt-4'>
      <%= link_to t('views.navigation.edit'), edit_car_category_path(@car_category), class: 'btn btn-primary' %>
      <%= link_to t('views.actions.delete'), @car_category, method: :delete, 
                  data: { confirm: t('views.messages.delete_resource', resource: @car_category.name) },
                  class: 'btn btn-danger' %>
    </div>
  </div>
</main>