config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'home#index'

  resources :manufacturers
  resources :subsidiaries
  resources :car_categories
  resources :customers
  resources :car_models
  resources :cars

  resources :rentals do
    collection do
      match :search, via: :get, as: :search_by_token
    end
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{!message_type ? message_type : 'info'}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= t('views.footer.message_1') %>
    <a href='https://github.com/librity'>Luis Geniole</a>
    <%= t('views.footer.message_2') %>
    <a href='https://treinadev.com.br/'>Treina Dev,</a>
    <%= t('views.footer.message_3') %>
    <a href='https://www.campuscode.com.br/'>Campus Code</a>, São Paulo.
  </small>

  <nav>
    <ul>
      <li>
        <a href='https://github.com/librity/campus_code_car_rental_system'>
          <%= t('views.footer.original_repo') %>
        </a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= favicon_link_tag 'favicon.ico' %>

  <title><%= t('views.application_name') %></title>
</head>

app/views/layouts/_headbar.html.erb
<header class='main_headbar navbar bg-dark'>
  <div class='container main_headbar_container'>
    <% if user_signed_in? %>
      <%= form_with url: search_by_token_rentals_path, local: true, method: "get", 
                    class: 'search_rentals_by_token_form' do |f| %>
        <div class="form-row align-items-center my-1">
          <div class="col-auto">
            <%= f.label :token, t('views.navigation.search_rentals_by_token'), class: 'sr-only' %>
            <%= f.search_field :token, placeholder: t('views.placeholders.search_rentals_by_token'), 
                                required: true, pattern: '[\w]{5}', class: 'form-control mb-2' %>
          </div>
          <div class="col-auto">
            <%= f.submit t('views.actions.search'), class: 'btn btn-outline-primary mb-2' %>
          </div>
        </div>
      <%- end %>
    <% end %>

    <div class="logo_container mb-2">
      <%= link_to image_tag("logo.svg", alt: t('views.application_name'), width: "40"), root_path, class: 'logo_svg' %>
      <%= link_to t('views.application_name'), root_path, class: 'logo_name' %>
    </div>

    <nav class='nav navbar-right'>

      <li class='nav-item'><%= link_to t('views.navigation.home'), root_path, class: 'header_nav_link' %></li>

      <% if user_signed_in? %>
        <li class='nav-item'><%= link_to t('views.actions.log_out'), destroy_user_session_path, method: :delete, 
                                         class: 'header_nav_link' %></li>

        <li class='nav-item header_nav_link'>
          <div class='dropdown'>
            <a class='nav-item dropdown-toggle' role='button' id='resourcesDropdown' 
              data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
              <%= t('views.navigation.resources') %>
            </a>
    
            <div class='dropdown-menu' aria-labelledby='resourcesDropdown'>
              <%= link_to t('activerecord.models.manufacturer.other'), manufacturers_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.car_category.other'), car_categories_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.car_model.other'), car_models_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.car.other'), cars_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.subsidiary.other'), subsidiaries_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.customer.other'), customers_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.rental.other'), rentals_path, class: 'dropdown-item' %>
            </div>
          </div>
        </li>
      <% else %>
        <li class='nav-item'><%= link_to t('views.navigation.log_in'), new_user_session_path, class: 'header_nav_link' %></li>
      <% end %>

    </nav>
  </div>
</header>

app/views/layouts/_headebar.html.erb
<header class='navbar navbar-expand-lg navbar-dark bg-dark'>
  <div class='container'>
    <div class="logo_container mb-2">
      <%= link_to image_tag("logo.svg", alt: t('views.application_name'), width: "40"), root_path, class: 'logo_svg' %>
      <%= link_to t('views.application_name'), root_path, class: 'logo_name' %>
    </div>

    <% if user_signed_in? %>
      <%= form_with url: search_by_token_rentals_path, local: true, method: "get" do |f| %>
        <div class="form-row align-items-center my-1">
          <div class="col-auto">
            <%= f.label :token, t('views.navigation.search_rentals_by_token'), class: 'sr-only' %>
            <%= f.search_field :token, placeholder: t('views.placeholders.search_rentals_by_token'), 
                                pattern: '[\w]{5}', class: 'form-control mb-2' %>
          </div>
          <div class="col-auto">
            <%= f.submit t('views.actions.search'), class: 'btn btn-outline-primary mb-2' %>
          </div>
        </div>
      <%- end %>
    <% end %>

    <nav class='nav navbar-right'>
      <li class='nav-item'><%= link_to t('views.navigation.home'), root_path, class: 'header_nav_link' %></li>

      <% if user_signed_in? %>
        <li class='nav-item'><%= link_to t('views.actions.log_out'), destroy_user_session_path, method: :delete, class: 'header_nav_link' %></li>

        <li class='nav-item header_nav_link'>
          <div class='dropdown'>
            <a class='nav-item dropdown-toggle' role='button' id='resourcesDropdown' 
              data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
              <%= t('views.navigation.resources') %>
            </a>
    
            <div class='dropdown-menu' aria-labelledby='resourcesDropdown'>
              <%= link_to t('activerecord.models.manufacturer.other'), manufacturers_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.car_category.other'), car_categories_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.car_model.other'), car_models_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.car.other'), cars_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.subsidiary.other'), subsidiaries_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.customer.other'), customers_path, class: 'dropdown-item' %>
              <%= link_to t('activerecord.models.rental.other'), rentals_path, class: 'dropdown-item' %>
            </div>
          </div>
        </li>
      <% else %>
        <li class='nav-item'><%= link_to t('views.navigation.log_in'), new_user_session_path, class: 'header_nav_link' %></li>
      <% end %>

    </nav>
  </div>
</header>

app/views/layouts/_header.html.erb
<header class='navbar navbar-expand-lg navbar-dark bg-dark'>
  <div class='container'>
    <div class="logo_container">
      <%= link_to image_tag("logo.svg", alt: t('views.application_name'), width: "40"), root_path, class: 'logo_svg' %>
      <%= link_to t('views.application_name'), root_path, class: 'logo_name' %>
    </div>

    <nav class='nav navbar-right'>
      <li class='nav-item'><%= link_to t('views.navigation.home'), root_path, class: 'header_nav_link' %></li>

      <li class='nav-item header_nav_link'>
        <div class='dropdown'>
          <a class='nav-item dropdown-toggle' role='button' id='resourcesDropdown' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            <%= t('views.navigation.resources') %>
          </a>
  
          <div class='dropdown-menu' aria-labelledby='resourcesDropdown'>
            <%= link_to t('activerecord.models.manufacturer.other'), manufacturers_path, class: 'dropdown-item' %>
            <%= link_to t('activerecord.models.car_category.other'), car_categories_path, class: 'dropdown-item' %>
            <%= link_to t('activerecord.models.car_model.other'), car_models_path, class: 'dropdown-item' %>
            <%= link_to t('activerecord.models.subsidiary.other'), subsidiaries_path, class: 'dropdown-item' %>
            <%= link_to t('activerecord.models.customer.other'), customers_path, class: 'dropdown-item' %>
          </div>
        </div>
      </li>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/headbar' %>

    <div class='container'>
      <%= render 'layouts/flash_messages' %>

      <%= yield %>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>